### ISSUE TITLE
IE8 compatibility?

### ISSUE THREAD

**Issue by mistergone** [cfpb/AtomicComponent#2]
@sebworks - Since the AtomicComponent script calls `Object.create`, it's not natively compatible with IE8. How do you recommend handling this? Specifically, how would you recommend handling this for a platform like `capital-framework`?

**Comment by sebworks** [comment]
>@sebworks - Since the AtomicComponent script calls Object.create, it's not natively compatible with IE8. How do you recommend handling this? Specifically, how would you recommend handling this for a platform like capital-framework?

We no longer support IE8 with JavaScript.

**Comment by mistergone** [comment]
Good enough - I feel like I can make an acceptable fallback for IE8 in `capital-framework`.
